a = [{'hostnames': [{'name': 'XiaoQiang', 'type': 'PTR'}], 'addresses': {'ipv4': '192.168.31.1', 'mac': '8C:DE:F9:3D:32:3F'}, 'vendor': {}, 'status': {'state': 'up', 'reason': 'arp-response'}, 'tcp': {22: {'state': 'closed', 'reason': 'reset', 'name': 'ssh', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 23: {'state': 'closed', 'reason': 'reset', 'name': 'telnet', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 24: {'state': 'closed', 'reason': 'reset', 'name': 'priv-mail', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 25: {'state': 'closed', 'reason': 'reset', 'name': 'smtp', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}}}, {'hostnames': [{'name': 'nova_8-ee5fdda7839cac92', 'type': 'PTR'}], 'addresses': {'ipv4': '192.168.31.19', 'mac': '92:E1:D9:00:44:CB'}, 'vendor': {}, 'status': {'state': 'up', 'reason': 'arp-response'}, 'tcp': {22: {'state': 'closed', 'reason': 'reset', 'name': 'ssh', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 23: {'state': 'closed', 'reason': 'reset', 'name': 'telnet', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 24: {'state': 'closed', 'reason': 'reset', 'name': 'priv-mail', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 25: {'state': 'closed', 'reason': 'reset', 'name': 'smtp', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}}}, {'hostnames': [{'name': 'PC-202104191109', 'type': 'PTR'}], 'addresses': {'ipv4': '192.168.31.222'}, 'vendor': {}, 'status': {'state': 'up', 'reason': 'localhost-response'}, 'tcp': {22: {'state': 'closed', 'reason': 'reset', 'name': 'ssh', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 23: {'state': 'closed', 'reason': 'reset', 'name': 'telnet', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 24: {'state': 'closed', 'reason': 'reset', 'name': 'priv-mail', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 25: {'state': 'closed', 'reason': 'reset', 'name': 'smtp', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}}}, {'hostnames': [{'name': 'rockchip', 'type': 'PTR'}], 'addresses': {'ipv4': '192.168.31.88', 'mac': '98:FC:84:8D:F1:5F'}, 'vendor': {}, 'status': {'state': 'up', 'reason': 'arp-response'}, 'tcp': {22: {'state': 'closed', 'reason': 'reset', 'name': 'ssh', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 23: {'state': 'closed', 'reason': 'reset', 'name': 'telnet', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 24: {'state': 'closed', 'reason': 'reset', 'name': 'priv-mail', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}, 25: {'state': 'closed', 'reason': 'reset', 'name': 'smtp', 'product': '', 'version': '', 'extrainfo': '', 'conf': '3', 'cpe': ''}}}]
for row in a:
    host_ip = (row.get("addresses")).get('ipv4')
    name = (row.get('hostnames')[0]).get('name')
    tcp_openPortlist = list(row.get('tcp').keys())
    temp_list = tcp_openPortlist.copy()
    print(temp_list)
    for portNumber in temp_list:
        portState = ((row.get('tcp')).get(portNumber)).get('state')
        tcp_openPortlist.append(portState)
    print(tcp_openPortlist)